# dpl v2
# https://docs.travis-ci.com/user/deployment-v2

language: node_js

node_js:
  - lts/*

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/

install:
  - npm ci

script:
  - npm run test

before_deploy:
  - cp ./dist/* .

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_token: $NPM_TOKEN
    edge: true
    on:
      tags: true
  - provider: releases
    token: $GITHUB_TOKEN
    edge: true
    on:
      tags: true

cache:
  directories:
    - '$HOME/.npm'
