language: node_js

node_js:
  - lts/*

branches:
  only:
    - master

install:
  - npm ci

script:
  - npm run test

before_deploy:
  - cp ./dist/* .

deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      tags: true
      all_branches: true
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    on:
      tags: true
      all_branches: true

cache:
  directories:
    - '$HOME/.npm'
